version: 2

sources:
  - name: raw
    schema: gwz_raw_data
    description: raw data
    tables:
      - name: product
        identifier: raw_gz_product
        description: product
      - name: sales
        identifier: raw_gz_sales
        description: sales
      - name: ship
        identifier: raw_gz_ship
        description: ship