version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / we have on row per product_id
        columns:
          - name: products_id
            description: pk / identifier of product
            data_tests:
              - unique
              - not_null
          - name: purchse_price
            description: cost of purchasing any given product
      - name: sales
        loaded_at_field: CAST(date_date AS TIMESTAMP)
        freshness:
          warn_after:
            {count: 90,
            period: day}
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of sale
          - name: orders_id
            description: corresponding order. order_id + products_id = pk
          - name: pdt_id
            description: the associated product. order_id + products_id = pk
          - name: revenue
            description: the revenue earned for these products in this sale
          - name: quantity
            description: the number of items defined in products_id
        tests:
          - unique:
              column_name: "(orders_id || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: deliveries of Greenweez / we have on row per orders_id
        columns:
          - name: orders_id
            description: pk of ship
            data_tests:
              - unique
              - not_null
          - name: shipping_fee
            description: euros we charged for shipping
          - name: log_cost
            description: the logistical cost incurred
          - name: ship_cost
            description: the shipping cost incurred
      - name: adwords
        identifier: gz_raw_adwords
        description: adwords data
        columns:
          - name: date_date
            description: date of campaign
          - name: paid_source
            description: the source of the campaign
          - name: campaign_key
            description: key for the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the ads
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: facebook
        identifier: gz_raw_facebook
        description: campaigns run of facebook
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: bing
        identifier: gz_raw_bing
        description: campaigns run on bing
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: criteo
        identifier: gz_raw_criteo
        description: campaigns run on criteo
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"